schema: sdd
created: 2026-05-20
specId: raven-spec-c5c0e1de-98ff-4096-af19-0697d03fcd21
status: coding-test
source:
  type: overmind
  issueKey: OMMUSIC-3480371
  url: https://music-overmind.hz.netease.com/1/requirement/issues/OMMUSIC-3480371
